- name: Install nemo
  ansible.builtin.apt:
    name:
      - nemo
    state: present

# - name: Use nemo to draw desktop icons
#   ansible.builtin.command:
#     cmd: "gsettings set org.gnome.desktop.background show-desktop-icons false"

# - name: Use nemo as default file manager
#   ansible.builtin.command:
#     cmd: "xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search"