- name: "Configure WSL Linux distro"
  hosts: wsl
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: Configure sudo
    import_tasks: ./wsl/sudo.yml
    tags:
    - sudo

  - name: Enable systemd
    import_tasks: ./wsl/systemd.yml
    tags:
    - systemd
    - yubikey

  - name: Install Docker
    import_tasks: ./wsl/docker.yml
    tags:
    - docker

  - name: Install Powerline shell
    tags:
    - powerline
    import_tasks: ./wsl/powerline-shell.yml

  - name: Install NodeJS development tools
    import_tasks: ./wsl/dev-nodejs.yml
    tags:
    - nodejs

  - name: Install Go development tools
    import_tasks: ./wsl/dev-golang.yml
    tags:
    - golang

  - name: Install .NET Core development tools
    import_tasks: ./wsl/dev-dotnetcore.yml
    tags:
    - dotnetcore

  - name: Configure Yubikey passthrough to WSL
    import_tasks: ./wsl/yubikey.yml
    tags:
    - yubikey

  - name: Install age encryption
    import_tasks: ./wsl/age.yml
    tags:
    - yubikey
    - age
    - sops

  - name: Install Terraform
    import_tasks: ./wsl/terraform.yml
    tags:
    - terraform

  - name: Install SOPS
    import_tasks: ./wsl/sops.yml
    tags:
    - sops

  - name: Install kubernetes tools
    import_tasks: ./wsl/kubernetes.yml
    tags:
    - kubernetes
    - k8s

  - name: Configure git
    import_tasks: ./wsl/git.yml
    tags:
    - git