- name: "Configure Windows host"
  hosts: win
  tasks:
  # - name: "Install basic utilities"
  #   import_tasks: "./windows/util-packages.yml"

  # - name: "Install Development tools"
  #   import_tasks: "./windows/dev-packages.yml"
  #   tags:
  #   - dev

  - name: "Install GPG packages"
    import_tasks: "./windows/yubikey.yml"
    tags:
    - yubikey