- name: "Configure Windows host"
  hosts: win
  tasks:
  - name: "Install basic utilities"
    import_tasks: "./windows/util-packages.yml"
    tags:
    - basic

  - name: "Install Development tools"
    import_tasks: "./windows/dev-packages.yml"
    tags:
    - dev

  - name: "Configure Yubikey passthrough to WSL"
    import_tasks: "./windows/yubikey.yml"
    tags:
    - yubikey

  - name: "Mount WSL home as network drive"
    import_tasks: "./windows/wsl-mount.yml"
    tags:
    - wsl-mount

  - name: "Clean up context menu items"
    import_tasks: "./windows/context-menu.yml"
    tags:
    - basic
    - dev
    - yubikey

  - name: "Clean up desktop shortcuts"
    import_tasks: "./windows/desktop-icons.yml"
    tags:
    - basic
    - dev
    - yubikey