- name: Uninstall undesired packages
  ansible.builtin.apt:
    name: 
        - libreoffice*
        - timeshift
        - snapd
    state: absent

- name: Disable snaps from installing back
  ansible.builtin.dpkg_selections:
    name: snapd
    selection: hold