- name: Create directory for authenticator state
  ansible.builtin.file:
    path: /var/lib/google-authenticator
    owner: root
    group: root
    mode: 0774
    state: directory

- name: Create directory for current's user authenticator state
  ansible.builtin.file:
    path: "/var/lib/google-authenticator/{{ lookup('env', 'USER') }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0770
    state: directory

- name: Notify user to set up google authenticator
  debug:
    msg: |
      Please do not forget to set up google authenticator for your user account using the command below:
      google-authenticator --secret=/var/lib/google-authenticator/{{ lookup('env', 'USER') }}/secret


# test if sufficient works with multiple factors or a substack is required

# - name: Add Google TOTP requirement when signing in with a password
#   ansible.builtin.lineinfile:
#     path: /etc/pam.d/common-password
#     create: false
#     # Required for out-of-home secret storage
#     # null ok may be skipped depending on a variable
#     line: "auth sufficient pam_google_authenticator.so secret=/var/lib/google-authenticator/${USER}/secret nullok"
