- name: Create directory for authenticator state
  ansible.builtin.file:
    path: /var/lib/google-authenticator
    owner: root
    group: root
    mode: 0774
    state: directory

- name: Create directory for current's user authenticator state
  ansible.builtin.file:
    path: "/var/lib/google-authenticator/{{ lookup('env', 'USER') }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0770
    state: directory

- name: Notify user to set up google authenticator
  debug:
    msg: |
      Please do not forget to set up google authenticator for your user account using the command below:
      google-authenticator --secret=/var/lib/google-authenticator/{{ lookup('env', 'USER') }}/secret


- name: Add Google TOTP requirement when signing in with a password
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-password
    create: false
    line: "auth sufficient pam_google_authenticator.so nullok"


# # TODO: Test after restart
# - name: Create scripts for locking the screen when YubiKey is removed
#   ansible.builtin.copy:
#     dest: "{{ item.dest }}"
#     content: "{{ lookup('ansible.builtin.file', item.src) }}"
#     owner: root
#     group: root
#     mode: 0775
#   loop:
#     - src: yubikey-removed-script
#       dest: /usr/local/bin/yubikey-removed-script
#     - src: yubikey-screenlock.rules
#       dest: /etc/udev/rules.d/yubikey-screenlock.rules