- name: Install Yubikey utilities
  ansible.builtin.apt:
    name: 
      - yubikey-manager
      - yubikey-manager-qt
      - yubico-piv-tool
      - yubikey-personalization-gui
      - yubioath-desktop

- name: Configure using YubiKey as SSH and GPG key
  ansible.builtin.include_tasks:
    file: ./security/yubikey-gpg.yaml

#- name: Configure sign in with Google OTP
#  ansible.builtin.include_tasks:
#    file: ./security/signin-google-otp.yaml

#- name: Configure sign in with Yubikey
#  ansible.builtin.include_tasks:
#    file: ./security/signin-yubikey.yaml

#- name: Configure sign in with fingerprints
#  ansible.builtin.include_tasks:
#    file: ./security/signin-fingerprint.yaml

#- name: Update pam.d to support new authentication factors
#  ansible.builtin.copy:
#    dest: /etc/pam.d/common-auth
#    force: true
#    owner: root
#    group: root
#    mode: 0644
#    content: "{{ lookup('ansible.builtin.file', 'pamd-common-authentication') }}"
