- name: Install required packages
  ansible.builtin.apt:
    name: 
      - libpam-u2f
      - pamu2fcfg

- name: Check if user has an u2f key set up
  ansible.builtin.stat:
      path: /var/lib/mfa/{{ lookup('env', 'USER') }}/.u2f_keys
  register: u2f_keys

- name: Fail if the user has no u2f keys set up
  ansible.builtin.fail:
    msg: |
      Please do not forget to set save mapping of your u2f key to your profile with the following command:
      pamu2fcfg > /var/lib/mfa/{{ lookup('env', 'USER') }}/.u2f_keys
  when: not u2f_keys.stat.exists

# Options
# - with PIN it could be used as a single factor - preferable
# - without PIN it can be used as a second factor

# - name: Add Yubikey requirement for sign in
#   ansible.builtin.lineinfile:
#     path: /etc/pam.d/common-password
#     create: false
#     # Required for out-of-home secret storage
#     # null ok may be skipped depending on a variable
#     line: "auth            sufficient                      pam_u2f.so expand authfile=/var/lib/mfa/%u/.u2f_keys nouserok interactive=1 pinverification=1 debug debug_file=/tmp/u2f.log"
# This only works as a second factor how to add it as the first one ???


- name: Create script for locking the screen when YubiKey is removed
  ansible.builtin.copy:
    dest: "/usr/local/bin/yubikey-removed-script"
    content: "{{ lookup('ansible.builtin.file', 'yubikey-removed-script') }}"
    owner: root
    group: root
    mode: 0775

- name: Create udev rule for locking the screen when YubiKey is removed
  ansible.builtin.copy:
    dest: "/etc/udev/rules.d/yubikey-screenlock.rules"
    content: "{{ lookup('ansible.builtin.file', 'yubikey-screenlock.rules') }}"
    owner: root
    group: root
    mode: 0664
