- name: Install SSH
  ansible.builtin.apt:
    name: ssh

- name: Add authorized ssh keys
  no_log: true
  ansible.posix.authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ ssh_public_keys }}"

- name: Configure SSH security
  ansible.builtin.include_role:
    name: geerlingguy.security
  vars:
    ansible_os_family: "Debian"
    security_ssh_password_authentication: "no"
    security_ssh_permit_root_login: "no"
    security_ssh_usedns: "no"
    security_ssh_permit_empty_password: "no"
    security_ssh_challenge_response_auth: "no"
    security_ssh_gss_api_authentication: "no"
    security_ssh_x11_forwarding: "no"
    security_ssh_allowed_users:
      - "{{ lookup('env', 'USER') }}"
