- name: Install browsers
  ansible.builtin.apt:
    name:
      - google-chrome-stable
      - vivaldi-stable
      - microsoft-edge-stable

- name: Install tools and utilities
  ansible.builtin.apt:
    name: 
      - vlc
      - spotify-client
      - default-jre # JRE
      - softmaker-freeoffice-2021
      - notepadqq
      - krita
      - krita-l10n
      - okular
      - cloudflare-warp
    state: present

- name: Install etcher
  ansible.builtin.include_tasks:
    file: ./reusable/install-latest-gh-release.yaml
  vars:
    gh_release_repo_slug: balena-io/etcher
    gh_release_package_file_pattern: balena-etcher_(.*)_amd64\.deb
  when: "'balena-etcher-electron' not in ansible_facts.packages"

- name: Install draw.io
  ansible.builtin.include_tasks:
    file: ./reusable/install-latest-gh-release.yaml
  vars:
    gh_release_repo_slug: jgraph/drawio-desktop
    gh_release_package_file_pattern: drawio-amd64-(.*)\.deb
  when: "'drawio' not in ansible_facts.packages"

- name: Install Slack
  ansible.builtin.apt:
    deb: "https://downloads.slack-edge.com/releases/linux/4.35.131/prod/x64/slack-desktop-4.35.131-amd64.deb"
  when: "'slack-desktop' not in ansible_facts.packages"

- name: Install Zoom
  ansible.builtin.apt:
    deb: "https://zoom.us/client/5.17.1.1840/zoom_amd64.deb"
  when: "'zoom' not in ansible_facts.packages"

- name: Install Duo Desktop
  ansible.builtin.apt:
    deb: "https://desktop.pkg.duosecurity.com/duo-desktop-latest.amd64.deb"
  when: "'duo-desktop' not in ansible_facts.packages"