- name: Install browsers
  ansible.builtin.apt:
    name:
      - google-chrome-stable
      - vivaldi-stable
      - microsoft-edge-stable

- name: Install tools and utilities
  ansible.builtin.apt:
    name: 
      - vlc
      - spotify-client
      - default-jre # JRE
      - softmaker-freeoffice-2021
      # From downloaded file - create a new partial to avoid downloading the installer each time
      # zoom
      # slack
      # PDF reader - foxit alternative ?
      # Krita (drawing)

  #  - Diff package - ???
  #  - Notepad++ (alternative ?)
    state: present

- name: Install etcher
  ansible.builtin.include_tasks:
    file: utils-etcher.yaml
  when: "'balena-etcher-electron' not in ansible_facts.packages"