- name: Notify user to set up google authenticator
  debug:
    msg: Please do not forget to set up google authenticator for your user account

- name: Add Google TOTP requirement when signing in with a password
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-password
    create: false
    line: "auth required pam_google_authenticator.so"


# # TODO: Test after restart
# - name: Create scripts for locking the screen when YubiKey is removed
#   ansible.builtin.copy:
#     dest: "{{ item.dest }}"
#     content: "{{ lookup('ansible.builtin.file', item.src) }}"
#     owner: root
#     group: root
#     mode: 0775
#   loop:
#     - src: yubikey-removed-script
#       dest: /usr/local/bin/yubikey-removed-script
#     - src: yubikey-screenlock.rules
#       dest: /etc/udev/rules.d/yubikey-screenlock.rules