- name: Install required packages
  ansible.builtin.apt:
    name: 
      - ssh
      - libpam-yubico
      - libpam-google-authenticator
      - yubikey-manager
      - yubikey-manager-qt
      - yubico-piv-tool
      - yubikey-personalization-gui
      - yubioath-desktop
      # For disk encryption
      - yubikey-luks
      # For screen lock when YK removed
      - finger
      # For SSH
      - scdaemon
      - pcscd

- name: Configure using YubiKey as SSH and GPG key
  ansible.builtin.include_tasks:
    file: yubikey-gpg.yaml

- name: Configure using YubiKey as a sign in and lock method
  ansible.builtin.include_tasks:
    file: yubikey-signin.yaml

# TODO: Sign in with fingerprint - must be set up on newer laptop