- name: Add apt key
  retries: 5
  register: apt_key_get_url
  until: (apt_key_get_url.status_code >= 200 and apt_key_get_url.status_code < 300) or apt_key_get_url.status_code == 304
  ansible.builtin.get_url:
    url: "{{ apt_key_url }}"
    dest: "{{ apt_key_dest }}"

- name: Add repository
  notify: Update apt cache
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.filename }}"
    update_cache: false
    state: present
  loop: "{{ apt_repos }}"