- name: Get latest version
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ gh_release_repo_slug }}/releases/latest"
    return_content: yes
  register: latest_version    

- name: Get matching files
  ansible.builtin.set_fact:
    latest_version_matching_files: "{{ (latest_version.content | from_json).assets | selectattr('name', 'match', gh_release_package_file_pattern) | map(attribute='browser_download_url') | select('string') | list }}"

- name: Verify exactly one file matches the pattern
  ansible.builtin.fail:
    msg: "Exactly one file must match the file pattern. Found matches: {{ latest_version_matching_files }}"
  when: (latest_version_matching_files | count) != 1