- name: Add Docker repository
  tags: [ dev ]
  ansible.builtin.import_tasks:
    file: ../reusable/add-repo.yaml
  vars:
    apt_key_url: https://download.docker.com/linux/ubuntu/gpg
    apt_key_dest: /etc/apt/trusted.gpg.d/docker.asc
    apt_repos:
      - repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_lsb_release.UBUNTU_CODENAME }} stable"
        filename: nodesource