- name: Add Google Chrome repository
  tags: [ utils ]
  ansible.builtin.import_tasks:
    file: ../reusable/add-repo.yaml
  vars:
    apt_key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    apt_key_dest: /etc/apt/keyrings/google.pub
    apt_repos:
      - repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/google.pub] http://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome