# Kubectl
- name: Fetch kubernetes version
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: true
  register: kubectl_version

- name: Fetch kubectl checksum
  ansible.builtin.uri:
    url: https://dl.k8s.io/{{ kubectl_version.content }}/bin/linux/amd64/kubectl.sha256
    return_content: true
  register: kubectl_checksum

- name: "Download kubectl"
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/{{ kubectl_version.content }}/bin/linux/amd64/kubectl
    checksum: "sha256:{{ kubectl_checksum.content }}"
    dest: /usr/local/bin/kubectl
    mode: 0755
    owner: root
    group: root

# Helm
- name: Install helm
  ansible.builtin.include_role:
    name: geerlingguy.helm

# Helm secrets
- name: Check if helm secrets are already installed
  register: helm_plugins
  ansible.builtin.command: helm plugin list

- name: Install helm secrets
  when: "'secrets' not in helm_plugins.stdout"
  ansible.builtin.command: helm plugin install https://github.com/jkroepke/helm-secrets

# Kubescape
- name: Fetch kubescape checksum
  ansible.builtin.uri:
    url: https://github.com/kubescape/kubescape/releases/latest/download/kubescape-ubuntu-latest.sha256
    return_content: true
  register: kubescape_checksum

- name: "Download kubescape"
  ansible.builtin.get_url:
    url: https://github.com/kubescape/kubescape/releases/latest/download/kubescape-ubuntu-latest
    checksum: "sha256:{{ kubescape_checksum.content }}"
    dest: /usr/local/bin/kubescape
    mode: 0755
    owner: root
    group: root