- name: Install required packages
  ansible.builtin.apt:
    name: 
      - libpam-u2f
      - pamu2fcfg

- name: Check if user has an u2f key set up
  ansible.builtin.stat:
      path: "{{ lookup('env', 'HOME') }}/.u2f_keys"
  register: u2f_keys

- name: Notify user to configure u2f keys
  when: not u2f_keys.stat.exists
  ansible.builtin.debug:
    msg:
      - "Please do not forget to set save mapping of your u2f key to your profile with the following command:"
      - "pamu2fcfg > {{ lookup('env', 'HOME') }}/.u2f_keys"

- name: Wait until u2f keys configured
  when: not u2f_keys.stat.exists
  ansible.builtin.wait_for:
    path: "{{ lookup('env', 'HOME') }}/.u2f_keys"
    msg: "U2F keys not configured, cannot continue"

