#!/usr/bin/env bash
# Locks the screen if a Yubikey is not plugged in

if ! env | grep DEVNAME; then
  exit 0;
fi

LOCKER="cinnamon-screensaver"
LOCKER_COMMAND="${LOCKER}-command"

getXuser() {
  user=`finger | grep -m1 ":$displaynum " | awk '{print $1}'`
  if [ x"$user" = x"" ]; then
    user=`finger| grep -m1 ":$displaynum" | awk '{print $1}'`
  fi
  if [ x"$user" != x"" ]; then
    userhome=`getent passwd $user | cut -d: -f6`
    export XAUTHORITY=$userhome/.Xauthority
  else
    export XAUTHORITY=""
  fi
}

for x in /tmp/.X11-unix/*; do
    displaynum=`echo $x | sed s#/tmp/.X11-unix/X## | sed s#/##`
    getXuser
    if [ x"$XAUTHORITY" != x"" ]; then
        # extract current state
        export DISPLAY=":$displaynum"
    fi
done

enable_timer=true

if [ "${enable_timer}" == "true" ]; then
  for i in {1..5}; do
    sleep 1;
    echo $(( $i*20 ));
  done | zenity --title "Yubikey removed" --text "Locking the screen\n(Press Escape to cancel)" --width 400 --progress --no-cancel --auto-close
  answer=$?
fi

if [[ "${enable_timer}" != "true" ]] || [[ ${answer} -eq 0 ]]; then
  logger "YubiKey Removed - Locking Workstation"
  su $user -c "/usr/bin/${LOCKER_COMMAND} -l"
fi