ansible_host: "{{ lookup('file', '/etc/resolv.conf').split() | last }}"
ansible_connection: winrm
ansible_winrm_transport: ntlm

ansible_winrm_server_cert_validation: ignore

ansible_winrm_scheme: http
ansible_port: 5985
